image: ubuntu

stages:
  - Lint
  - Build
  - Test

Pylint:
  stage: Lint
  image: codacy/codacy-pylint
  script:
    - pylint *

Install Dependencies:
  stage: Build
  script:
    - pip install -r requirements.txt

Hello World:
  stage: Test
  script:
    - echo "Hello!"
    
