image: ubuntu

stages:
  - Lint
  - Build
  - Test

Pylint:
  stage: Lint
  image: codacy/codacy-pylint
  script:
    - ls
    - pylint ./
  allow_failure: true

Install Dependencies:
  stage: Build
  script:
    - pip install -r requirements.txt
  allow_failure: true

Hello World:
  stage: Test
  script:
    - echo "Hello!"
  allow_failure: true